# Defines the entire serverless detection pipeline—the CloudTrail, the S3 bucket for logs, the EventBridge rule, and the SNS topic for alerts—as code

AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Deploys a cloud-native intrusion detection pipeline. It uses CloudTrail,
  EventBridge, and SNS to send an email alert when the sts:GetCallerIdentity
  API call is made.

Parameters:
  AlertEmailAddress:
    Type: String
    Description: The email address to which security alerts will be sent.

Resources:
  # S3 Bucket for CloudTrail Logs
  CloudTrailBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  CloudTrailBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref CloudTrailBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: 'AWSCloudTrailAclCheck'
            Effect: Allow
            Principal: {Service: 'cloudtrail.amazonaws.com'}
            Action: 's3:GetBucketAcl'
            Resource: !GetAtt CloudTrailBucket.Arn
          - Sid: 'AWSCloudTrailWrite'
            Effect: Allow
            Principal: {Service: 'cloudtrail.amazonaws.com'}
            Action: 's3:PutObject'
            Resource: !Sub '${CloudTrailBucket.Arn}/AWSLogs/${AWS::AccountId}/*'
            Condition:
              StringEquals: {'s3:x-amz-acl': 'bucket-owner-full-control'}

  # CloudTrail to log all management events
  APITrail:
    Type: AWS::CloudTrail::Trail
    Properties:
      S3BucketName: !Ref CloudTrailBucket
      IsLogging: true
      IsMultiRegionTrail: true
      IncludeGlobalServiceEvents: true
      EnableLogFileValidation: true

  # SNS Topic for sending alerts
  AlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: 'APICallAlertTopic'
      TopicName: 'APICallAlertTopic'

  # SNS Subscription to send alerts to the specified email
  EmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      Endpoint: !Ref AlertEmailAddress
      TopicArn: !Ref AlertTopic

  # EventBridge Rule to detect the specific API call
  GetCallerIdentityAlertRule:
    Type: AWS::Events::Rule
    Properties:
      Name: 'GetCallerIdentityAlert'
      Description: 'Triggers an alert when sts:GetCallerIdentity is called'
      EventPattern:
        source:
          - 'aws.sts'
        detail-type:
          - 'AWS API Call via CloudTrail'
        detail:
          eventName:
            - 'GetCallerIdentity'
      Targets:
        - Arn: !Ref AlertTopic
          Id: 'SNSTarget'

  # Policy to allow EventBridge to publish to the SNS Topic
  SNSTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref AlertTopic
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: {Service: 'events.amazonaws.com'}
            Action: 'sns:Publish'
            Resource: !Ref AlertTopic

Outputs:
  AlertTopicARN:
    Description: 'ARN of the SNS topic for alerts'
    Value: !Ref AlertTopic
